services:
  # Odoo Application Service
  web:
    image: odoo:18.0
    depends_on:
      - haproxy
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - DB_HOST=haproxy  # Use HAProxy as DB host
      - DB_PORT=5432
    secrets:
      - postgresql_password

  # PostgreSQL Primary Database
  db_primary:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-primary-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

  # PostgreSQL Standby Database (Hot Standby)
  db_standby:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    depends_on:
      - db_primary
    volumes:
      - db-standby-data:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c wal_level=replica
               -c hot_standby=on
               -c primary_conninfo="host=db_primary port=5432 user=odoo password=$(cat /run/secrets/postgresql_password)"
    secrets:
      - postgresql_password

  pgbouncer:
    image: edoburu/pgbouncer
    depends_on:
      - db_primary
      - db_standby
    environment:
      - DB_HOST=db_primary  # Set the DB host for PgBouncer
      - DATABASES=primary=host=db_primary port=5432 standby=host=db_standby port=5432
      - AUTH_USER=odoo
      - AUTH_PASSWORD_FILE=/run/secrets/postgresql_password  # Use the secret for AUTH_PASSWORD
    ports:
      - "6432:6432"
    secrets:
      - postgresql_password




  # HAProxy for Failover and Routing
  haproxy:
    image: haproxy:2.5
    depends_on:
      - db_primary
      - db_standby
    ports:
      - "5435:5432"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  odoo-web-data:
  db-primary-data:
  db-standby-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass  # Your secret file location
