version: '3'

services:
  odoo:
    image: odoo:18.0
    deploy:
      replicas: 2
    environment:
      - HOST=haproxy
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
    depends_on:
      - haproxy

  haproxy:
    image: haproxy:latest
    ports:
      - "5432:5432" # PostgreSQL port
      - "10000:9999"  # Change the pgPool port to avoid conflict
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - pgpool

  pgpool:
    image: pgpool/pgpool:latest
    environment:
      - PGPOOL_BACKEND_NODES=0=db1:5432,1=db2:5432
      - PGPOOL_PORT=9999
    ports:
      - "9999:9999"  # pgPool port inside the container
    depends_on:
      - db1
      - db2

  db1:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db1-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  db2:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db2-data:/var/lib/postgresql/data
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge

volumes:
  db1-data:
  db2-data:
