version: '3.7'

services:
  # PostgreSQL Primary Database
  db_primary:
    image: postgres:17.2
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
      POSTGRES_DB: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - odoo_network

  # PostgreSQL Standby Database (for high availability)
  db_standby:
    image: postgres:17.2
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
    volumes:
      - db_standby_data:/var/lib/postgresql/data
    networks:
      - odoo_network

  # HAProxy for Load Balancing (PostgreSQL)
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5432:5432"  # PostgreSQL port for Odoo
    networks:
      - odoo_network

  # Odoo Service
  web:
    image: odoo:18.0
    environment:
      - DB_HOST=haproxy
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo_password
      - DB_NAME=odoo
    depends_on:
      - db_primary
      - db_standby
      - haproxy
    volumes:
      - odoo_data:/mnt/odoo
    ports:
      - "8069:8069"
    networks:
      - odoo_network

volumes:
  db_data:
  db_standby_data:
  odoo_data:

networks:
  odoo_network:
    driver: bridge
